services:
  adgaurd:
    image: docker.io/adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped
    ports:
      # Admin Portal (only for initial setup)
      # - 3333:3000/tcp 
      # WebUI
      - 8080:80/tcp
      # DNS
      - 53:53/tcp
      - 53:53/udp
    environment:
      - TZ=${TZ:?ERROR! Please provide the timezone!!!}
    volumes:
      - adguard_data_work:/opt/adguardhome/work
      - adguard_data_conf:/opt/adguardhome/conf
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80/']
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  adguard_data_work:
  adguard_data_conf:
