services:
  adgaurd:
    image: docker.io/adguard/adguardhome:latest
    container_name: adguard
    restart: unless-stopped
    ports:
      - 3333:3000/tcp
      - 8080:80/tcp # 80 reserved for reverse proxy
      - 53:53/tcp
      - 53:53/udp
      # # DNS-over-TLS
      - "853:853/tcp"
      # # DNS-over-QUIC
      - "853:853/udp"
    volumes:
      - ./adguard_data/work:/opt/adguardhome/work
      - ./adguard_data/conf:/opt/adguardhome/conf
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:80/']
      interval: 60s
      timeout: 10s
      retries: 5
      start_period: 30s
